### ISSUE TITLE
How to set up a game - Overhaul

### ISSUE THREAD

**Issue by Bob-Murphy** [official-antistasi-community/A3-Antistasi-Docs#44]
@targetingsnake Please overhaul the `How to setup a game` section with the content below.
Unfortunately have no time to put it into a proper format. Sorry about that.

```
How to set up a game

Single Player / Locally Hosted
- Subscribe to the `Antistasi Mod <https://steamcommunity.com/sharedfiles/filedetails/?id=2867537125>`__
- Load the Antistasi Mod in the Arma 3 Launcher
- Start Arma 3
- Go to Server Browser --> Host new Session
- Select a compatible map and then select the mission called `Antistasi Community [Version number]` in white text.
- If you play on your own, make sure you pick the `Default Commander` slot as this one has the medic as well as the engineer perk.


(Dedicated) Server
- Install the Antistasi Mod on your server. How you go about this is depending on your server setup. Some servers have the ability to directly subscribe to a Steam Workshop Item. In this case subscribe to the `Antistasi Mod <https://steamcommunity.com/sharedfiles/filedetails/?id=2867537125>`__ via your server. In case your server does not have this functionality, you likely have to upload the files manually to the server. You find the most up to date files `here <github.com/official-antistasi-community/A3-Antistasi/releases/latest>`__ . Download the rar, unpack it and upload the content via FTP to your server.
- Make sure you load the Antistasi Mod. This is usually done via commandline. How exactly again is depending on your server setup. Please consult the documentation available for your service or contact their support, if applicable.
- When you now start the server, you should be able to manually select the missions called `Antistasi Community [Version number]`, laod it and play.
- If you want to set the server up to automatically load the Antistasi mission after a restart, that can be done using the mission cycle in the server.cfg like in the following example.

```
// MISSIONS CYCLE (see below)
class Missions {
    class Mission1    {
        template ="Antistasi_mapname.mapname";
        difficulty = "Regular"; //can be Recruit, Regular, Veteran or Custom. Custom needs setting up though.
        class Params {
            autoLoadLastGame = 60; //Automatically starts the mission 60 seconds after the first player connected to the server and no admin is logged in. {"No automatic load","1min","2min","3min","5min","10min"}
            LogLevel = 2; //Sets the log level during the setup. {"Error", "Info", "Debug", "Verbose"}
            A3A_logDebugConsole = 1; //Sets the Log debug console use during setup. {"None", "All non-dev", "All"}
        };
    };
};
```

`Antistasi_mapname.mapname` oneeds to be replaced with the appropriate mapname based on which map you want to play.
Here the available ones:

`Antistasi_Altis.Altis` - for Altis
`Antistasi_tem_anizay.tem_anizay` - for Anizay
`Antistasi_cam_lao_nam.cam_lao_nam` - for Cam Lao Nam
`Antistasi_chernarus.chernarus` - for Chernarus Autumn
`Antistasi_chernarus_summer.chernarus_summer` - for Chernarus Summer
`Antistasi_chernarus_winter.chernarus_winter` - for Chernarus Winter
`Antistasi_vn_khe_sanh.vn_khe_sanh` - for Khe Sanh
`Antistasi_Kunduz.Kunduz` - for Kunduz
`Antistasi_Enoch.Enoch` - for Livonia
`Antistasi_Malden.Malden` - for Malden
`Antistasi_sara.sara` - for Sahrani
`Antistasi_Takistan.takistan` - for Takistan
`Antistasi_Tanoa.Tanoa` - for Tanoa
`Antistasi_Tembelan.Tembelan` - for Tembelan Island
`Antistasi_vt7.vt7` - for Virolahti 
```

**Comment by jaj22** [comment]
Under the SP/localhost section:
- Only one Antistasi mod should be loaded at a time.
- All clients must load the same Antistasi mod as the host.

Under "Install the Antistasi mod on your server":
- You can also upload the client workshop mod from your PC. The latest github release is identical.
- When using FTP, make sure binary rather than text or auto transfer mode is selected.

Under "Make sure you load the Antistasi mod":
- Only one Antistasi mod should be loaded at a time.
- The mod should be loaded as a general mod (-mod), not as a server mod (-servermod). Different servers have different names for these.
- Clients must load the same Antistasi mod as the server.

Under "When you now start the server":
- The vast majority of server providers seem to have an empty mission cycle by default, which means you just get a blank loading screen on connection rather than the selection UI.
- To get to the mission selection UI in this case, you must log in as admin and then use the server command `#missions`.
- To log in as admin, use the server command `#login adminpassword`. The admin password is in your server config file.
- Server commands (such as #login or #missions) are entered in the text chat box. The default text chat key is the slash (/) key.
- Once the mission has been started, log in as admin to see the setup UI. Voted admins do not count.
